FROM rocker/r-base

RUN apt-get update && apt-get install -y \
	r-base \
	libssl-dev \
	libcurl4-openssl-dev \
	libxml2-dev \
	zlib1g-dev \
	libbz2-dev

RUN R -e "install.packages('BiocManager', repos = 'http://cran.rstudio.com/')"

RUN R -e "BiocManager::install(c('rhdf5', 'tximeta'))"
