FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
        tzdata \
        r-base \
        libssl-dev \
        libcurl4-openssl-dev \
        libxml2-dev \
        zlib1g-dev \
        libbz2-dev 

RUN R -e "install.packages(c('BiocManager','remotes'), repos = 'http://cran.rstudio.com/')"
RUN R -e "BiocManager::install(c('rhdf5', 'tidyverse', 'optparse', 'ggplot2', 'RColorBrewer', 'pheatmap'))"
RUN R -e "remotes::install_github('pachterlab/sleuth')"